services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"  # Maps host port 3000 to container port 80 (Nginx)
    volumes:
      - ./frontend/src:/app/src  # For development hot-reloading
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "8000:8000"  # Maps host port 8000 to container port 8000 (FastAPI)
    volumes:
      - ./backend/model:/app/model  # Mounts the model directory
      - ./backend/customer_churn_dataset-training-master.csv:/app/customer_churn_dataset-training-master.csv  # Mounts the dataset
    networks:
      - app-network

networks:
  app-network:
    driver: bridge